import type {
  User,
  Goal,
  Milestone,
  LegacyEntry,
  Connection,
  RtgEvent,
  Challenge,
  MembershipApplication,
  Achievement,
} from "./types";

/**
 * Seed data. Written to feel real — this is the demo world of Road to Glory.
 * Profile images are gradient seeds resolved by <Avatar/> (no external assets).
 */

export const currentUser: User = {
  id: "u_self",
  fullName: "Marcus Vale",
  username: "marcusvale",
  profileImage: "gold-01",
  archetype: "Entrepreneur",
  bio: "Building at the edge of ambition. Two exits, one obsession: compounding excellence.",
  city: "Monaco",
  country: "MC",
  gloryScore: 8420,
  levelOfGreatness: "Titan",
  membershipTier: "Inner Circle",
  verified: true,
  inviteCode: "RTG-VALE-7X2",
  onboardingCompleted: true,
  focusAreas: ["Business", "Wealth", "Health", "Legacy"],
  createdAt: "2024-02-11T09:00:00Z",
};

export const members: User[] = [
  {
    id: "u_2",
    fullName: "Isabel Cortez",
    username: "icortez",
    profileImage: "gold-02",
    archetype: "Investor",
    bio: "Early capital for outliers. Board seats in 4 continents.",
    city: "London",
    country: "GB",
    gloryScore: 9210,
    levelOfGreatness: "Sovereign",
    membershipTier: "Founding Member",
    verified: true,
    inviteCode: "RTG-CORT-2A1",
    onboardingCompleted: true,
    focusAreas: ["Wealth", "Impact"],
    createdAt: "2023-11-02T09:00:00Z",
  },
  {
    id: "u_3",
    fullName: "Dario Fenn",
    username: "dfenn",
    profileImage: "gold-03",
    archetype: "Athlete",
    bio: "Two-time world tour podium. Discipline is a love language.",
    city: "Zürich",
    country: "CH",
    gloryScore: 7640,
    levelOfGreatness: "Gladiator",
    membershipTier: "Member",
    verified: true,
    inviteCode: "RTG-FENN-9K3",
    onboardingCompleted: true,
    focusAreas: ["Health", "Mindset"],
    createdAt: "2024-05-19T09:00:00Z",
  },
  {
    id: "u_4",
    fullName: "Naomi Adeyemi",
    username: "nadeyemi",
    profileImage: "gold-04",
    archetype: "Creator",
    bio: "Culture architect. 40M audience. Turning attention into legacy.",
    city: "New York",
    country: "US",
    gloryScore: 8890,
    levelOfGreatness: "Visionary",
    membershipTier: "Inner Circle",
    verified: true,
    inviteCode: "RTG-ADEY-5T8",
    onboardingCompleted: true,
    focusAreas: ["Impact", "Personal Mastery"],
    createdAt: "2024-01-08T09:00:00Z",
  },
  {
    id: "u_5",
    fullName: "Julian Roth",
    username: "jroth",
    profileImage: "gold-05",
    archetype: "Top Executive",
    bio: "Scaled two orgs past $1B. Operator's operator.",
    city: "Berlin",
    country: "DE",
    gloryScore: 8010,
    levelOfGreatness: "Titan",
    membershipTier: "Member",
    verified: true,
    inviteCode: "RTG-ROTH-4Q9",
    onboardingCompleted: true,
    focusAreas: ["Business", "Mindset"],
    createdAt: "2024-03-27T09:00:00Z",
  },
  {
    id: "u_6",
    fullName: "Sofia Marchetti",
    username: "smarchetti",
    profileImage: "gold-06",
    archetype: "Artist",
    bio: "Contemporary sculptor. Collected across three continents.",
    city: "Milan",
    country: "IT",
    gloryScore: 7320,
    levelOfGreatness: "Vanguard",
    membershipTier: "Selected",
    verified: false,
    inviteCode: "RTG-MARC-1B6",
    onboardingCompleted: true,
    focusAreas: ["Legacy", "Personal Mastery"],
    createdAt: "2024-06-30T09:00:00Z",
  },
];

export const goals: Goal[] = [
  {
    id: "g_1",
    userId: "u_self",
    title: "Scale the fund to $250M AUM",
    category: "Business",
    description: "Institutionalize the raise, close two anchor LPs, build the platform team.",
    currentLevel: 3,
    targetLevel: 5,
    progress: 64,
    visibility: "club",
    deadline: "2026-12-31",
    nextAction: "Finalize the anchor LP term sheet",
    actionSteps: [
      { id: "s1", label: "Data room v2 complete", done: true },
      { id: "s2", label: "Anchor LP diligence call", done: true },
      { id: "s3", label: "Close $80M first tranche", done: false },
      { id: "s4", label: "Hire Head of Platform", done: false },
    ],
    createdAt: "2025-01-10T09:00:00Z",
  },
  {
    id: "g_2",
    userId: "u_self",
    title: "Sub-3:00 marathon",
    category: "Health",
    description: "Build the aerobic base and race a certified course under three hours.",
    currentLevel: 2,
    targetLevel: 4,
    progress: 48,
    visibility: "allies",
    deadline: "2026-04-19",
    nextAction: "Log the 32km long run",
    actionSteps: [
      { id: "s1", label: "Base phase — 6 weeks", done: true },
      { id: "s2", label: "Threshold block", done: false },
      { id: "s3", label: "Race simulation", done: false },
    ],
    createdAt: "2025-03-02T09:00:00Z",
  },
  {
    id: "g_3",
    userId: "u_self",
    title: "Establish a family foundation",
    category: "Legacy",
    description: "Structure a foundation with a 20-year education mandate.",
    currentLevel: 1,
    targetLevel: 4,
    progress: 22,
    visibility: "private",
    nextAction: "Draft the founding charter",
    actionSteps: [
      { id: "s1", label: "Define the mandate", done: true },
      { id: "s2", label: "Legal structure", done: false },
      { id: "s3", label: "First grant cycle", done: false },
    ],
    createdAt: "2025-05-21T09:00:00Z",
  },
  {
    id: "g_4",
    userId: "u_self",
    title: "Master public speaking",
    category: "Personal Mastery",
    description: "Keynote three summits and command a room of a thousand.",
    currentLevel: 2,
    targetLevel: 5,
    progress: 40,
    visibility: "club",
    nextAction: "Confirm Vision Summit keynote slot",
    actionSteps: [
      { id: "s1", label: "Coaching intensive", done: true },
      { id: "s2", label: "Two rehearsed talks", done: true },
      { id: "s3", label: "Keynote a flagship summit", done: false },
    ],
    createdAt: "2025-02-14T09:00:00Z",
  },
];

export const feed: Milestone[] = [
  {
    id: "m_1",
    userId: "u_2",
    title: "Closed a $40M growth round",
    description: "Led the round into a category-defining climate company. Board seat secured.",
    achievedAt: "2026-07-05T14:00:00Z",
    verified: true,
    type: "accomplishment",
    category: "Wealth",
    reactions: { trophy: 214, respect: 88, salute: 41, powerMove: 132 },
  },
  {
    id: "m_2",
    userId: "u_3",
    title: "Podium — World Tour Finals",
    description: "Second place after a 9-month rebuild from injury. The comeback is the story.",
    achievedAt: "2026-07-04T18:30:00Z",
    verified: true,
    type: "milestone",
    category: "Health",
    reactions: { trophy: 512, respect: 190, salute: 260, powerMove: 74 },
  },
  {
    id: "m_3",
    userId: "u_4",
    title: "Attended — Monaco Founder Dinner",
    description: "An evening with twelve of the most relentless operators in Europe.",
    achievedAt: "2026-07-03T21:00:00Z",
    verified: true,
    type: "event",
    reactions: { trophy: 96, respect: 52, salute: 33, powerMove: 61 },
  },
  {
    id: "m_4",
    userId: "u_5",
    title: "Promoted to Group CEO",
    description: "Nine years, three turnarounds. Stewardship of 4,000 people begins.",
    achievedAt: "2026-07-02T11:00:00Z",
    verified: true,
    type: "accomplishment",
    category: "Business",
    reactions: { trophy: 341, respect: 205, salute: 88, powerMove: 150 },
  },
  {
    id: "m_5",
    userId: "u_6",
    title: "Lesson — On slow work",
    description: "The commission I almost declined became my most collected series. Patience compounds.",
    achievedAt: "2026-07-01T10:00:00Z",
    verified: false,
    type: "lesson",
    category: "Personal Mastery",
    reactions: { trophy: 44, respect: 121, salute: 18, powerMove: 22 },
  },
];

export const legacyEntries: LegacyEntry[] = [
  {
    id: "l_1",
    userId: "u_self",
    title: "The exit I walked away from",
    category: "Business",
    reflection:
      "At 29 I turned down a life-changing acquisition because the number flattered my ego more than my mission. It cost me two hard years. It bought me a company I'm proud of. Conviction is expensive and worth every cent.",
    symbol: "◆",
    createdAt: "2026-05-18T09:00:00Z",
  },
  {
    id: "l_2",
    userId: "u_self",
    title: "What the injury taught me",
    category: "Health",
    reflection:
      "A torn tendon took my season. It gave me a decade. I learned that the body keeps the score you refuse to read, and that recovery is a discipline, not a pause.",
    symbol: "△",
    createdAt: "2026-03-11T09:00:00Z",
  },
  {
    id: "l_3",
    userId: "u_self",
    title: "The mentor I lost too early",
    category: "Legacy",
    reflection:
      "He told me legacy is what you build in people, not in press. I write this so I never forget who taught me to think in decades.",
    symbol: "✦",
    createdAt: "2026-01-22T09:00:00Z",
  },
];

export const connections: Connection[] = [
  { id: "c_1", requesterId: "u_2", receiverId: "u_self", status: "connected", circleType: "Power Ring", createdAt: "2025-09-01T09:00:00Z" },
  { id: "c_2", requesterId: "u_self", receiverId: "u_4", status: "connected", circleType: "Ally", createdAt: "2025-10-11T09:00:00Z" },
  { id: "c_3", requesterId: "u_5", receiverId: "u_self", status: "connected", circleType: "Mastermind", createdAt: "2025-11-20T09:00:00Z" },
  { id: "c_4", requesterId: "u_6", receiverId: "u_self", status: "pending", circleType: "Ally", createdAt: "2026-07-01T09:00:00Z" },
  { id: "c_5", requesterId: "u_self", receiverId: "u_3", status: "suggested", circleType: "Ally", createdAt: "2026-07-04T09:00:00Z" },
];

export const events: RtgEvent[] = [
  {
    id: "e_1",
    title: "Lamborghini Club Race",
    category: "Track Day",
    description:
      "An invitation-only track day at Monza. Members drive, dine trackside, and close deals at 300 km/h. Curated grid of twenty.",
    image: "carbon",
    location: "Autodromo Nazionale Monza",
    city: "Monza",
    startAt: "2026-09-14T09:00:00Z",
    endAt: "2026-09-14T20:00:00Z",
    accessTier: "Inner Circle",
    hostId: "u_5",
    rsvpCount: 17,
    capacity: 20,
    dressCode: "Racing casual",
  },
  {
    id: "e_2",
    title: "Monaco Founder Dinner",
    category: "Private Dinner",
    description:
      "A twelve-seat dinner above the harbour. Founders only, one table, three hours, no phones.",
    image: "harbour",
    location: "Hôtel de Paris — Private Salon",
    city: "Monaco",
    startAt: "2026-07-28T19:30:00Z",
    endAt: "2026-07-28T23:30:00Z",
    accessTier: "Member",
    hostId: "u_2",
    rsvpCount: 11,
    capacity: 12,
    dressCode: "Black tie optional",
  },
  {
    id: "e_3",
    title: "Vision Summit",
    category: "Digital Summit",
    description:
      "A day of unfiltered strategy from operators who've built at scale. Streamed to members worldwide.",
    image: "aurora",
    location: "Streamed — Global",
    city: "Digital",
    startAt: "2026-08-05T15:00:00Z",
    endAt: "2026-08-05T21:00:00Z",
    accessTier: "Member",
    hostId: "u_4",
    rsvpCount: 240,
    capacity: 500,
  },
  {
    id: "e_4",
    title: "Elite Athletic Retreat",
    category: "Performance Camp",
    description:
      "Four days in the Alps with world-class coaches. Train, recover, recalibrate the machine.",
    image: "alpine",
    location: "Andermatt",
    city: "Andermatt",
    startAt: "2026-10-02T08:00:00Z",
    endAt: "2026-10-06T18:00:00Z",
    accessTier: "Founding",
    hostId: "u_3",
    rsvpCount: 8,
    capacity: 16,
    dressCode: "Performance kit",
  },
];

export const challenges: Challenge[] = [
  {
    id: "ch_1",
    title: "75 Days of Discipline",
    description: "Two workouts, one deep-work block, zero excuses. Daily.",
    category: "Mindset",
    progressMetric: "Day 41 of 75",
    progress: 55,
    duration: "75 days",
    rewardType: "Discipline badge — Elite",
    participants: 128,
  },
  {
    id: "ch_2",
    title: "Founders' Mile",
    description: "Run a sub-6:00 mile before quarter's end.",
    category: "Health",
    progressMetric: "6:24 best",
    progress: 70,
    duration: "Q3",
    rewardType: "Performance token",
    participants: 64,
  },
];

export const membershipApplication: MembershipApplication = {
  id: "ma_1",
  userId: "u_self",
  referralSource: "Isabel Cortez — Founding Member",
  applicationStatus: "peer_review",
  reviewNotes: "Strong founder profile. Two Inner Circle endorsements received. Final peer panel scheduled.",
  submittedAt: "2026-06-20T09:00:00Z",
  stages: [
    { label: "Application", done: true, active: false },
    { label: "Referral verified", done: true, active: false },
    { label: "Peer review", done: false, active: true },
    { label: "Admission", done: false, active: false },
  ],
};

export const achievements: Achievement[] = [
  { id: "a_1", title: "First Milestone", category: "Progress", icon: "◆", rarity: "Standard", description: "Completed your first tracked milestone.", unlocked: true },
  { id: "a_2", title: "Sub-3 Marathon", category: "Health", icon: "⚡", rarity: "Elite", description: "Broke three hours over 42.2km.", unlocked: false },
  { id: "a_3", title: "Founding Circle", category: "Status", icon: "✦", rarity: "Mythic", description: "Among the first hundred members.", unlocked: true },
  { id: "a_4", title: "Deal Maker", category: "Wealth", icon: "◈", rarity: "Rare", description: "Closed a verified nine-figure milestone.", unlocked: true },
  { id: "a_5", title: "Room Commander", category: "Mastery", icon: "▲", rarity: "Rare", description: "Keynoted a flagship summit.", unlocked: false },
  { id: "a_6", title: "Legacy Keeper", category: "Legacy", icon: "❖", rarity: "Elite", description: "Logged ten defining reflections.", unlocked: false },
];
